name: Day 3 CI
on:
  push:
  pull_request:
jobs:
  python_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Lint with flake8
        run: flake8 .
      - name: Run pytest
        run: |
          pytest -q
      - name: Deployment Step
        run: |
          echo "Deploying Application..."
          mkdir -p deploy
          cp Day3_CICD/app.py deploy/
          echo "Deployment complete!"
  bash_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run ShellCheck on scripts
        run: |
          set -e
          if compgen -G "Day2_Scripting/*.sh" > /dev/null; then
            find Day2_Scripting -type f -name "*.sh" -print0 | xargs -0 -r shellcheck -S warning
          else
            echo "No shell scripts found in Day2_Scripting"
          fi
  powershell_lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      - name: Analyze PowerShell scripts
        shell: pwsh
        run: |
          if (Test-Path "Day1_Linux_Git/backup.ps1") {
            Invoke-ScriptAnalyzer -Path "Day1_Linux_Git/backup.ps1" -Recurse -Severity Warning
          } else {
            Write-Output "No PowerShell scripts to analyze"
          }
  notify:
    if: always()
    needs: [python_checks, bash_shellcheck, powershell_lint]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        if: ${{ secrets.SLACK_WEBHOOK != ' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
