name: Day 3 CI (full)
on:
  push:
  pull_request:
jobs:
  python_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Lint with flake8 (Day3 only)
        run: |
          flake8 Day3_CI_CD Day3_CICD
      - name: Run pytest (Day3 only)
        run: |
          pytest -q Day3_CI_CD Day3_CICD
  bash_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run ShellCheck on scripts (non-fatal warnings)
        run: |
          set -e
          if compgen -G "Day2_Scripting/*.sh" > /dev/null; then
            find Day2_Scripting -type f -name "*.sh" -print0 | xargs -0 -r shellcheck -S warning || true
          else
            echo "No shell scripts found in Day2_Scripting"
          fi
  powershell_lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      - name: Analyze PowerShell scripts
        shell: pwsh
        run: |
          if (Test-Path "Day1_Linux_Git/backup.ps1") {
            Invoke-ScriptAnalyzer -Path "Day1_Linux_Git/backup.ps1" -Recurse -Severity Warning
          } else {
            Write-Output "No PowerShell scripts to analyze"
          }
  notify:
    if: always()
    needs: [python_checks, bash_shellcheck, powershell_lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check Slack configured
        id: slack
        env:
          WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [ -n "$WEBHOOK" ]; then
            echo "configured=true" >> $GITHUB_OUTPUT
          else
            echo "configured=false" >> $GITHUB_OUTPUT
          fi
      - name: Slack Notification
        if: ${{ steps.slack.outputs.configured == 'true' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
